### ISSUE TITLE
Question on License

### ISSUE THREAD

**Issue by mtmarsh2** [AKSHAYUBHAT/ImageSegmentation#2]
Hi Akshaybhat! I found your project through here: https://news.ycombinator.com/item?id=9944133 and in one of the comments, you mentioned the project would be released under an open source license, but it looks like its copyright. Is the project open source?

**Comment by Petah** [comment]
Any update on this?

**Comment by AKSHAYUBHAT** [comment]
@mtmarsh2 @Petah  Done!
