### ISSUE TITLE
Can't run in https://www.eraseimage.com/

### ISSUE THREAD

**Issue by AlianOL** [AKSHAYUBHAT/ImageSegmentation#4]
hello  AKSHAYUBHAT,
   I don't know why your https://www.eraseimage.com/ can't add image or make other operations,I really need the function to solve some proplem, so can you do some help for me?

**Comment by AKSHAYUBHAT** [comment]
Are you using the latest version of Chrome, you can check browser inspector console to make sure some js is not missing/not loaded. I check right now and its working. 

https://www.dropbox.com/s/mszbt61g9zr36yr/Screenshot%202017-04-27%2001.20.12.png?dl=0

**Comment by AlianOL** [comment]
e..thanks,now It works Correctly,Exactly some js didn't load,because China's Internet is not World Internet,haha..
