### ISSUE TITLE
how can I run this project?

### ISSUE THREAD

**Issue by junedgar** [AKSHAYUBHAT/ImageSegmentation#5]
hi, i tried to run the project, but i failed. I installed all the requirements  in the requirements.txt.  I'm sorry to trouble you.

**Comment by AKSHAYUBHAT** [comment]
you don't need any to install requirements in requirements.txt. All you need is simple local server that renders index.html and ensures that all .js / .css files are loaded correctly from the folders. 

See this issue for example 
https://github.com/AKSHAYUBHAT/ImageSegmentation/issues/3

You don't even need firebase.

**Comment by junedgar** [comment]
@AKSHAYUBHAT thank you for your help!!!

**Comment by mrgloom** [comment]
So, how to run the project? Looks like directly openning ImageSegmentation-master\firebaseapp\public\index.html doesnt't work.

**Comment by AKSHAYUBHAT** [comment]
install firebase and run
`
 firebase serve
`
