### ISSUE TITLE
Many /dist files cannot be found

### ISSUE THREAD

**Issue by RickyWong33** [AKSHAYUBHAT/ImageSegmentation#6]
![404](https://user-images.githubusercontent.com/5317425/33270486-2f99cab8-d3bf-11e7-8fc6-bd8d06f03601.png)

As you see
```
GET /static/dist/js/app.min.js 404 0.573 ms - 38
GET /static/dist/css/AdminLTE.min.css 404 0.685 ms - 45
GET /static/dist/css/skins/_all-skins.min.css 404 1.839 ms - 53
GET /static/dist/js/app.min.js 404 0.544 ms - 38
GET /favicon.ico 404 1.306 ms - 24
GET /static/dist/css/AdminLTE.min.css 404 0.761 ms - 45
GET /static/dist/css/skins/_all-skins.min.css 404 0.601 ms - 53
```

there are no `/static/dist` dir, how can I generage them?

**Comment by RickyWong33** [comment]
in your `.gitignore` setting, you have ignored the `dist/` dir, so how can I build the javascript?
Or can you upload the `dist/` dir?

**Comment by bogdanBo** [comment]
You can copy this files from [https://www.eraseimage.com/](https://www.eraseimage.com/)

**Comment by RickyWong33** [comment]
OK， thanks
